dist: focal  # используем Ubuntu 20.04
sudo: required  # используем Virtual Machine

language: c
os: linux
compiler: gcc

install:
  # cmake, clang-format, valgrind, lcov
  - sudo apt update
  - sudo apt install clang-format
  - sudo apt install valgrind
  - sudo apt install cmake
  - sudo apt install lcov
  # add cppcheck linter
  - sudo apt install cppcheck
  # GTest
  - sudo apt install libgtest-dev
  # configure after installation
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - cd -

before_script:
  # before running, let's apply clang-format
  - clang-format -i -style=Google *.c
  - cd hw2_static/src
  - clang-format -i -style=Google *.c
  - cd ../../hw2_shared/src
  - clang-format -i -style=Google *.c
  - cd ../../include
  - clang-format -i -style=Google *.h
  - cd ../test
  - clang-format -i -style=Google *.cpp
  - cd ../stress_test
  - clang-format -i -style=Google *.cpp
  - cd ..
  # apply cppcheck linter
  - cppcheck hw2_shared/ hw2_static/ include/ main.c --inconclusive --enable=all --error-exitcode=1 --language=c
  - cppcheck test/ stress_test/ --inconclusive --enable=all --error-exitcode=1 --language=c++
  # generate stress test file
  - cd stress_test
  - python3 stress_test_generation.py
  - cd ..

script:
  - cmake .
  - make || travis_terminate 1
  - ./hw2_with_static stress_test/stress_test.txt
  - ./hw2_with_shared stress_test/stress_test.txt
  - cd test
  - valgrind --error-exitcode=1 --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med --track-origins=yes ./unit_tests_with_static || travis_terminate 1
  - valgrind --error-exitcode=1 --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med --track-origins=yes ./unit_tests_with_shared || travis_terminate 1
  - cd ../stress_test
  - valgrind --error-exitcode=1 --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med --track-origins=yes ./stress_test || travis_terminate 1
  - cd ..
  # measure execution time
  - cd stress_test
  - ./measure_static
  - ./measure_shared
  - cd ..

after_script:
  - lcov --capture --directory ./hw2_static/CMakeFiles/hw2_static_lib.dir --output-file coverage_static.info
  - lcov --capture --directory ./hw2_shared/CMakeFiles/hw2_shared_lib.dir --output-file coverage_shared.info
  # merging two coverages into one file
  - lcov -a coverage_static.info -a coverage_shared.info -o total.info
  - bash <(curl -s https://codecov.io/bash) -f total.info || echo "Codecov did not collect coverage reports"