dist: focal  # используем Ubuntu 20.04
sudo: required  # испоьлзуем Virtual Machine

language: c
os: linux
compiler: gcc

install:
  # cmake, clang-form, valgrind
  - sudo apt update
  - sudo apt install clang-format
  - sudo apt install valgrind
  - sudo apt install cmake
  # GTest
  - sudo apt install libgtest-dev
  # configure after installation
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - cd -

before_script:
  # before running, let's apply clang-format
  - cd src
  - clang-format -i -style=Google *.h *.c
  - cd ../test
  - clang-format -i -style=Google *.cpp

script:
  - cmake .
  - make || travis_terminate 1
  - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med  --track-origins=yes test_string || travis_terminate 1
  - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med  --track-origins=yes test_filter || travis_terminate 1
